### ISSUE TITLE
More information about the Trace Replayer

### ISSUE THREAD

**Issue by LinqLover** [ExplorViz/frontend#3]
Hi! I discovered this project during my literature research as I would like to explore dynamic software visualizations further in my own research. I read a few times about the trace replayer but could not find any detailed information about it online (just a single paragraph & screenshot [in the thesis](https://macau.uni-kiel.de/servlets/MCRFileNodeServlet/dissertation_derivate_00006321/diss_fittkau.pdf#page=149)). Would it maybe be possible to provide further information about this feature?

- How does the animation look like? Does the visualization show any features specific to the selected execution step?
- Is it possible to use the trace replayed from the demo page (I did not find it)?
- Are there any additional screenshots or screencasts of the animation?

I would appreciate your support very much!

**Comment by Alexander-Krause-Glau** [comment]
Hi @LinqLover ,

> How does the animation look like? Does the visualization show any features specific to the selected execution step?
the trace replayer is currently disabled. However, I attached a screenshot (of an old commit) that shows the (`Right Click -> Open Sidebar` ) sidebar menu with an opened trace replayer.

Clicking on a trace will result in a camera focus on the first method call in the trace, i.e., a single communication line. You can then step through the trace while the camera will automatically focus the respective communication line. We currently show  `Callee`, `Caller` and `execution time` for a single step.

![grafik](https://user-images.githubusercontent.com/9912468/236002152-db56d98b-52d1-44a2-8161-e3a1aaa11ea2.png)

> Is it possible to use the trace replayed from the demo page (I did not find it)?

Unfortunately no, since it is currently buggy due to architectural changes.

> Are there any additional screenshots or screencasts of the animation?
There are currently no animation effects for meshes in ExplorViz. The camera simply focuses the currently selected step of a trace.

I hope this helps. What exactly are you looking for?

**Comment by LinqLover** [comment]
Thank you a lot for the detailed reply! As my literature research continues, it turns out that I was searching for something like the [night mode in EvoSpaces](https://ieeexplore.ieee.org/document/4639052). These are both very interesting concepts. :-)
